# Generated by Django 5.1.6 on 2025-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('fechaPublicacion', models.DateTimeField(auto_now=True)),
                ('resumen', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=200)),
                ('foto', models.CharField(max_length=150)),
                ('estadoPublicado', models.BooleanField(default=True)),
            ],
        ),
    ]
