# Generated by Django 5.1.6 on 2025-03-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='Titulo',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='detalle',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fechaPublicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='resumen',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(default='titulo', max_length=80),
            preserve_default=False,
        ),
    ]
