# Generated by Django 5.1.6 on 2025-03-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLocal', models.CharField(max_length=60)),
                ('nombreVisitante', models.CharField(max_length=60)),
                ('ganador', models.CharField(max_length=60)),
                ('odd', models.FloatField()),
                ('apuesta', models.IntegerField()),
                ('premio', models.IntegerField()),
                ('finalizada', models.BooleanField(default=False)),
                ('idFixture', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=25)),
            ],
        ),
    ]
