# Generated by Django 5.1.6 on 2025-03-02 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFutbol', '0002_remove_apuesta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
