# Generated by Django 5.1.6 on 2025-03-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiFutbol', '0003_apuesta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuesta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='apuesta',
            name='fecha',
        ),
    ]
