# Generated by Django 5.1.6 on 2025-03-02 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFutbol', '0004_remove_apuesta_estado_remove_apuesta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='estado',
            field=models.CharField(default='En juego', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apuesta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
